### ISSUE TITLE
Timepicker not working in safari

### ISSUE THREAD

**Issue by chiragshah-mb** [jonthornton/jquery-timepicker#470]
Timepicker not working in safari.

Works well in chrome on MAC.

JQuery version: 1.11.3

**Comment by jonthornton** [comment]
I wasn't able to find any issues with Safari 9.0.2 (11601.3.9). Can you provide more information?

**Comment by thedanielforum** [comment]
I have the same problem.
The list with times appear and you can "select" the times from the list, but they do not populate the input.

Device: IPad Air
OS: 9.0.2
Browser: Safari = Not working
Browser: Chrome = Not working
Browser: Opera Coast = Not working

JQuery version: 2.1.4

<img width="319" alt="screen shot 2016-02-18 at 11 12 45" src="https://cloud.githubusercontent.com/assets/3816627/13131695/93e28a70-d630-11e5-8835-4c4e2f1cf595.png">

**Comment by JustBlah** [comment]
This issue was fixed in [this pull request](https://github.com/jonthornton/jquery-timepicker/pull/496). The reason why you can't select an option with mobile device is that Timepicker is only listening to `mousedown` & `mouseup` events. If you want get this work you can use [my forked repo](https://github.com/JustBlah/jquery-timepicker) (with 1.8.11 tag) till this pull request is merged.

**Comment by jonthornton** [comment]
Fixed by #496
