### ISSUE TITLE
00:00 not selected / highlighted in dropdown

### ISSUE THREAD

**Issue by dnando** [jonthornton/jquery-timepicker#532]
Given a 24 hour timepicker that traverses midnight with show24 set to false (which is the default, but just for clarity's sake):

$("#nightRateStartTime").timepicker({
    'minTime': '18:00',
    'maxTime': '02:00',
    'step': 30,
    'timeFormat':'H:i',
    'show2400': false
});

Midnight represented as 00:00 is not selected and highlighted in the dropdown when the value of the field is set to 00:00. If the value of the same field is set to any other value, for example 23:30, that value is correctly selected and highlighted.

See screenshots attached:

![screen shot 2016-06-09 at 00 02 56](https://cloud.githubusercontent.com/assets/554655/15912646/dc10d7f0-2dd5-11e6-827f-5eeed6370b42.png)

![screen shot 2016-06-09 at 00 00 53](https://cloud.githubusercontent.com/assets/554655/15912640/d0338694-2dd5-11e6-80ad-7be774a56022.png)

![screen shot 2016-06-09 at 00 07 41](https://cloud.githubusercontent.com/assets/554655/15912740/7148e04c-2dd6-11e6-8002-d8e7abbc110d.png)

**Comment by rubenve** [comment]
The problem is that _render sets the value of the 'time' data attribute to 86400:
`row.data('time', (timeInt <= 86400 ? timeInt : timeInt % 86400));`

 and _findRow searches for 0 because it calls roundingFunction to determine the value to search for:
`var value = settings.roundingFunction(value, settings);`

roundingFunction returns 0 because of this code:
```				
if (seconds == _ONE_DAY && settings.show2400) {
	return seconds;
}

return seconds%_ONE_DAY;
```

Therefore the 00:00 row is never found by _findRow and is never selected.

I don't know if the idea is to actually use 0 or 86400 as the true value for 00:00 and so it depends on that what function should be modified to fix this issue.

**Comment by jonthornton** [comment]
@rubenve thank you for that hint!
