### ISSUE TITLE
 TimePicker need to click two time to load items in Internet Explorer Ask Question up vote

### ISSUE THREAD

**Issue by ayushtchetu** [jonthornton/jquery-timepicker#682]
I am using timepicker on my page to load time slots(e.g. 8am, 8.15am, 8.30 am and so on) like dropdown list. It is working fine in chrome or mozilla browser but when I test in Internet Explorer and when I clicked on textbox nothing happened. Then I clicked somewhere else on page and then again when I am clicking on time picker textbox then it is working fine and loading time slots. Following is my code-
On HTML
` <input type="text" asp-for="StartTime" class=" form-control calender-ico timepicker" id="StartDate" onkeydown="return false;">`

On javascript section-
```
 $(document).ready(function () {
DateSelect();
          function DateSelect() {
                $('#StartDate').timepicker(
                    {
                        'minTime': '@Model.MinTime.ToString()',
                        'step': '15',
                        'maxTime': '@Model.MaxTime.ToString()'
                     });
                     }
})
```
What is wrong here?

**Comment by jonthornton** [comment]
Microsoft [no longer supports Internet Explorer](https://support.microsoft.com/en-us/windows/internet-explorer-help-23360e49-9cd3-4dda-ba52-705336cc0de2), which will make it hard to test and support timepicker in Internet Explorer. While there may still be users impacted by this, I'm going to close the issue since the impact should continue to shrink.
