### ISSUE TITLE
ES6 "const" keyword introduced in 1.13.5

### ISSUE THREAD

**Issue by simshaun** [jonthornton/jquery-timepicker#720]
Not sure if this was intentional on jquery-timepicker's side.
https://github.com/jonthornton/jquery-timepicker/blob/1.13.5/src/jquery.timepicker.js#L30-L31

It's been causing problems in our build system that checks for ES6 keywords in output.

**Comment by jonthornton** [comment]
Thanks for the heads up! I'm planning to slowly convert `src` to ES6, but will continue publishing an ES5 compatible package. This is broken in 1.13.5 (still getting the hang of a new build system 😬 ) but fixed in https://github.com/jonthornton/jquery-timepicker/commit/a53e4efcdabfb5316c3ee50ac5123ddbf72d8405

You'll find an ES5 build here https://github.com/jonthornton/jquery-timepicker/blob/1.13.8/jquery.timepicker.js

**Comment by simshaun** [comment]
Thank you!
